### PR TITLE
#28, #32: fix for {@value} tags and {@see} tags for methods

### PR DESCRIPTION
**Pull request by bbottema**
See #28 and #32.

### CODE REVIEW

**Comment by bbottema** [comment]
Actually it's trickier than I thought. With `@value`, a field can be referenced implicitly without "#". I'll account for this scenario as well.

**Comment by dnault** [comment]
How about this case from the [documentation](https://docs.oracle.com/javase/7/docs/technotes/tools/windows/javadoc.html#value)?

> When `{@value}` is used (without any argument) in the doc comment of a static field, it displays the value of that constant:

```
/**
 * The value of this constant is {@value}.
 */
public static final String SCRIPT_START = "<script>"
```

**Comment by bbottema** [comment]
Nice, I didn't know about that one. I always used to qualify the constant and get a warning about it :)

I'll account for this scenario as well.

**Comment by bbottema** [comment]
SeeAlsoJavadoc now supports [all three modes](https://docs.oracle.com/javase/7/docs/technotes/tools/windows/javadoc.html#see) and works for Methods (#32). I have not touched the parsing for {@see} tags on Classes, so that probably still only works with links (separate issue though).

**Comment by bbottema** [comment]
This was a quick implementation, but I just realized that the `SeeAlsoJavadoc` class might be better off as an interface or abstract class with a generic and then a subclasses for each type. Just give it some thought.

Current implementation already works fine though (for methods level {@see} tags).

**Comment by bbottema** [comment]
Hi @dnault, I'm finishing up on my usage of this library and it is shaping up very nicely. This library is a life saver for me, but I do need these last changes for that. Are you planning on merging and releasing in the nearby future?

**Comment by dnault** [comment]
Hi @bbottema, thanks for the prod. Version 0.9.0 with your changes is released and available from Maven Central.

**Pull request merged**
